trigger: none
pr: none

variables:
- template: vars.yml

parameters:
- name: subscriptionId
  type: string
  default: ""

jobs:
- job: Ad_hoc_Action
  pool:
    name: ARO-CI

  steps:
  - template: ./templates/template-setup-golang-env.yml
    parameters:
      gobin: ${{ variables.GOBIN }}
      gopath: ${{ variables.GOPATH }}
      goroot: ${{ variables.GOROOT }}
      modulePath: ${{ variables.modulePath }}

  - template: ./templates/template-az-cli-login.yml
    parameters:
      workingDirectory: ${{ variables.modulePath }}
      azureDevOpsJSONSPN: $(aro-v4-e2e-devops-spn)

  - script: |
      set -e
      cd ${{ variables.modulePath }}

      az account set -s $(subscriptionId)
      az group list -o table
      az vmss delete -n rp-vmss-a87941f6 -g aro-int-eastus
      az vmss delete -n rp-vmss-bf928d67 -g aro-int-eastus
      az vmss delete -n rp-vmss-de63b69f -g aro-int-eastus

    displayName: ⚙️ Ad-hoc action

