# Azure DevOps Pipeline building swagger and publish it to artifacts for
# MSSwagger to consume
trigger: none
pr: none

variables:
- template: vars.yml

jobs:
- job: Build_and_push_swagger
  pool:
    name: ARO-CI

  steps:
  - task: PublishOpenApiDocument@0
    inputs:
      serviceName: 'Azure Red Hat OpenShift'
      publishSource: 'Git'
      sourceGitAccount: 'msazure'
      sourceGitProjectName: 'AzureRedHatOpenShift'
      sourceGitRepositoryName: 'ARO-RP-Mirror'
      sourceGitPath: '/swagger/redhatopenshift/resource-manager/Microsoft.RedHatOpenShift/stable/2020-04-30/redhatopenshift.json'
      sourceGitEncoding: 'utf8'
      useSystemAccessToken: true
      serviceCatalogId: $(service-catalog-id)
      microsoftSwaggerEnvironment: 'Production'