trigger: none
pr: none

parameters:
- name: dryRun
  type: boolean
  default: true

variables:
- template: vars.yml

jobs:
- job: Clean_subscription
  pool:
    vmImage: ubuntu-latest

  steps:
  - template: ./templates/template-setup-golang-env.yml
    parameters:
      gobin: ${{ variables.GOBIN }}
      gopath: ${{ variables.GOPATH }}
      goroot: ${{ variables.GOROOT }}
      modulePath: ${{ variables.modulePath }}

  - template: ./templates/template-clean-subscription.yml
    parameters:
      dryRun: ${{ parameters.dryRun }}
      subscriptionCredentials: ${{ variables.subscriptionCredentials }}
      subscriptionId: ${{ variables.subscriptionId }}
      purgeTTL: ${{ variables.purgeTTL }}
      purgeCreatedTag:  ${{ variables.purgeCreatedTag }}
      resourceGroupDeletePrefixes: ${{ variables.resourceGroupDeletePrefixes }}
      workingDirectory: ${{ variables.modulePath }}

