trigger: none
pr: none

variables:
- template: vars.yml

extends:
  template: ./templates/template-clean-subscription.yml
  parameters:
    purgeTTL: '48h'
    keepTag: 'DONOTTOUCH'
    dryRun: true
    workingDirectory: ${{ variables.modulePath }}
    subscriptionCredential: $(aro-rhdev-purge)
    subscriptionId: $(rh-subscription)
