# Azure DevOps Pipeline building swagger and publish it to artifacts for
# MSSwagger to consume
trigger: none
pr: none

variables:
- template: vars.yml

jobs:
- job: Sync_to_vsts_mirror
  pool:
    name: ARO-CI

  steps:
  - template: ./templates/template-checkout.yml
  - script: |
      git fetch origin
      git push https://$(vsts-token)@$(mirror-location) origin/master:master --force
    displayName: Mirror ARO-RP
