# Azure DevOps Pipeline building swagger and publish it to artifacts for
# MSSwagger to consume
trigger: none
pr: none

variables:
- template: vars.yml

jobs:
- job: Sync_to_vsts_mirror
  pool:
    name: ARO-CI

  steps:
  - template: ./templates/template-checkout.yml
  - script: |
      git fetch origin --all
      git push https://$(vsts-token)@$(mirror-location) master:master
    displayName: Mirror ARO-RP
